### PR TITLE
Lint fixes

### LINKED ISSUE #100: fix ignored lint errors in deployment-server-ui + cdtcloud

### PR DESCRIPTION
**Pull request by KevinK-9**
## Changes Proposed:

- added eslint fixes

## Issues Addressed:

- Closes #100 

## Tests Performed:

- ran application and went through different scenarios to see if it still works

## How to Test the Changes:

1. run on your system
2. test different scenarios of deploying/ monitoring etc.

## Known Issues and TODO List:

- [ ] review ignored lint errors
- [x] new issues in deployment-server-ui still need to be addressed in this PR

## How to Test PRs
1) First fetch the Pull-Request from the main repo, replacing `xx` with the ID of the PR:\
`git fetch git@github.com:eclipsesource/cdtcloud-deploymentserver.git pull/xx/head:pr_xx`
2) Checkout the Pull-Request, again replacing `xx` with the PR-ID:\
`git checkout pr_xx`
3) Perform the necessary tests for the PR

### CODE REVIEW

File: packages/deployment-server-ui/src/services/WebsocketService.ts [hunk 1]
```diff
@@ -26,17 +26,24 @@ const createWebsocket = async (route: string): Promise<WebSocket> => {
...
 }
 
-export const useWebsocket = (route: string, condition: boolean = true) => {
+export const useWebsocketFunction = (route: string, condition: boolean = true): {
+  open: boolean
+  subs: Array<((message: ServerMessage) => void)>
+  attempts: number
+  send: Function | undefined
+  subscribe: (eventFun: (resp: ServerMessage) => Promise<void>) => () => void
+  close: Function | undefined
```
Comment (Gozzim) [inline packages/deployment-server-ui/src/services/WebsocketService.ts:35]:
```suggestion
  open: boolean
  subs: Array<(message: ServerMessage) => void>
  attempts: number
  send: (payload: any) => void
  subscribe: (eventFun: (resp: ServerMessage) => void) => () => void
  close: () => void
```

File: packages/deployment-server-ui/src/pages/Devices.tsx [hunk 2]
```diff
@@ -139,13 +139,14 @@ export default defineFunctionalComponent(function Devices () {
...
-  ) {
+  ): void {
     const params: Record<string, string | string[]> = {
       status: [],
       deviceTypeId: []
     }
     setFilters(filters)
     for (const [key, value] of Object.entries(filters)) {
+      // eslint-disable-next-line @typescript-eslint/restrict-plus-operands
       if (value != null) params[key] = value.map((val) => '' + val)
```
Comment (Gozzim) [inline packages/deployment-server-ui/src/pages/Devices.tsx:150]:
```suggestion
      if (value != null) params[key] = value.map((val) => val.toString())
```

File: packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx [hunk 3]
```diff
@@ -210,22 +214,15 @@ export class CdtcloudWidget extends ReactWidget {
   }
 
   private startPollingDeployments (): void {
+    // eslint-disable-next-line @typescript-eslint/no-misused-promises
     this.interval = setInterval(async () => {
```
Comment (Gozzim) [inline packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx:218]: Could use the setIntervalAsync module instead. But it is fine for now.

**Review by Gozzim — CHANGES_REQUESTED** [review]
Just a quick review and a few minor comments

**Review by Gozzim — APPROVED** [review]
